/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.AdminWorkAreas;

import Business.Person.Person;
import Business.Person.PersonDirectory;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anirudh
 */
public class AdminWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form AdminWorkArea
     */
    public AdminWorkArea() {
        initComponents();
        populateUserTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnViewPerson = new javax.swing.JButton();
        btnViewPerson1 = new javax.swing.JButton();
        btnViewPerson2 = new javax.swing.JButton();
        btnViewPerson3 = new javax.swing.JButton();
        btnViewPerson4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPerson = new javax.swing.JTable();

        jSplitPane1.setDividerLocation(180);

        btnViewPerson.setText("View Person");
        btnViewPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPersonActionPerformed(evt);
            }
        });

        btnViewPerson1.setText("Attach Role");
        btnViewPerson1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPerson1ActionPerformed(evt);
            }
        });

        btnViewPerson2.setText("View Users");

        btnViewPerson3.setText("View Programs");

        btnViewPerson4.setText("View Professors");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewPerson4)
                    .addComponent(btnViewPerson3)
                    .addComponent(btnViewPerson2)
                    .addComponent(btnViewPerson1)
                    .addComponent(btnViewPerson))
                .addGap(29, 29, 29))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnViewPerson, btnViewPerson1, btnViewPerson2, btnViewPerson3, btnViewPerson4});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(btnViewPerson)
                .addGap(62, 62, 62)
                .addComponent(btnViewPerson1)
                .addGap(64, 64, 64)
                .addComponent(btnViewPerson2)
                .addGap(59, 59, 59)
                .addComponent(btnViewPerson3)
                .addGap(57, 57, 57)
                .addComponent(btnViewPerson4)
                .addContainerGap(324, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        tblPerson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "PersonID", "Name", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPerson);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(521, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(309, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void populateUserTable()
    {
//                ArrayList<Assignment> courseAssignments = AssignmentDirectory.findAssignmentForCourse(course.getCourseId());
        DefaultTableModel model = (DefaultTableModel) tblPerson.getModel();
        model.setRowCount(0);
        
        
        for(Person person : PersonDirectory.personlist)
        {
            Object[] row = new Object[3];
            row[0] = person.getPersonId();
            row[1] = person.getPersonName();
            row[2] = person.getPersonStatus();
            
        } 
    }
    
    
    private void btnViewPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPersonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewPersonActionPerformed

    private void btnViewPerson1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPerson1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewPerson1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewPerson;
    private javax.swing.JButton btnViewPerson1;
    private javax.swing.JButton btnViewPerson2;
    private javax.swing.JButton btnViewPerson3;
    private javax.swing.JButton btnViewPerson4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable tblPerson;
    // End of variables declaration//GEN-END:variables
}
