/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.StudentWorkAreas;

import UserInterface.FacultyWorkAreas.FacultyDashboardJPanel;
import UserInterface.FacultyWorkAreas.FacultyDirectUpdateAssignmentJPanel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.courses.Assignment;
import model.courses.AssignmentDirectory;
import model.courses.Course;
import model.courses.Schedule;
import model.student.StudentAssignmentDirectory;
import model.student.StudentDirectory;

/**
 *
 * @author anirudh
 */
public class AssignmentsListJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AssignmentsListJPanel
     */
    Course course;
    public AssignmentsListJPanel(Course course) {
        initComponents();
        this.course = course;
        populateAssignmentTable();
    }





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAssignments = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        tblAssignments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "AssignmentID", "Title", "Due By", "Actual Score", "Total points", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAssignments);

        jButton1.setText("Open Assignment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Assignments");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(479, 479, 479)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(487, 487, 487)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(293, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jButton1)
                .addContainerGap(238, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void populateAssignmentTable()
    {
        ArrayList<Assignment> courseAssignments = AssignmentDirectory.findAssignmentForCourse(course.getCourseId());
        DefaultTableModel model = (DefaultTableModel) tblAssignments.getModel();
        model.setRowCount(0);
        System.out.println(courseAssignments.size());
        
        for(Assignment assignment : courseAssignments)
        {
            Object[] row = new Object[6];
            row[0] = assignment.getAssignmentId();
            row[1] = assignment.getTitle();
            row[2] = assignment.getDueDate();
            row[3] = "";     
            row[4] = assignment.getTotalMarks();
            System.out.println(StudentAssignmentDirectory.findSubmission(assignment.getAssignmentId(), StudentDirectory.currentUser.getStudentId()));
            if(StudentAssignmentDirectory.findSubmission(assignment.getAssignmentId(), StudentDirectory.currentUser.getStudentId()))
                    
                row[5] = "Submitted";
            else
                row[5] = "Pending";
            model.addRow(row);  
            
        } 
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblAssignments.getSelectedRow();
        if(selectedRow >= 0)
        {

            {   
//                System.out.println(selectedRow);
//                System.out.println((Integer)tblAssignments.getValueAt(selectedRow, 0));
                Assignment assignment = AssignmentDirectory.findAssignment((Integer)tblAssignments.getValueAt(selectedRow, 0));
//                
                EachAssignmentJPanel panel = new EachAssignmentJPanel(assignment, course);
                EachCourseJPanel.jSplitPane1.setRightComponent(panel);
                
            }
            
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please select an assignment to update");
        } 

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAssignments;
    // End of variables declaration//GEN-END:variables
}
