/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.StudentWorkAreas;

import UserInterface.StudentWorkAreas.AssignmentsListJPanel;
import java.io.File;
import javax.swing.JFileChooser;
import model.courses.Assignment;
import model.courses.Course;
import model.student.StudentAssignment;
import model.student.StudentAssignmentDirectory;
import model.student.StudentDirectory;

/**
 *
 * @author anirudh
 */
public class EachAssignmentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EachAssignmentJPanel
     */
    Course course;
    Assignment assignment;
    String filename;
    public EachAssignmentJPanel(Assignment assignment, Course course) {
        initComponents();
        this.assignment = assignment;
        this.course = course;
        populateAssignmentFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSubmitAssignments = new javax.swing.JButton();
        lblDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        lblDescription1 = new javax.swing.JLabel();
        txtDueDate = new javax.swing.JTextField();
        lblDescription2 = new javax.swing.JLabel();
        txtTotalPoints = new javax.swing.JTextField();
        lblDescription3 = new javax.swing.JLabel();
        txtFileString = new javax.swing.JTextField();
        btnUploadAssignment = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Assignment Title");

        btnSubmitAssignments.setText("Submit Assignment");
        btnSubmitAssignments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitAssignmentsActionPerformed(evt);
            }
        });

        lblDescription.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblDescription.setText("Description: ");

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        lblDescription1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblDescription1.setText("Due date: ");

        lblDescription2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblDescription2.setText("Total points: ");

        lblDescription3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblDescription3.setText("Upload Assignment: ");

        txtFileString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFileStringActionPerformed(evt);
            }
        });

        btnUploadAssignment.setText("Upload Assignment");
        btnUploadAssignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadAssignmentActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblDescription)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblDescription1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblDescription2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTotalPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSubmitAssignments))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblDescription3)
                            .addGap(12, 12, 12)
                            .addComponent(txtFileString, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnUploadAssignment))))
                .addContainerGap(357, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(lblDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescription1)
                    .addComponent(txtDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescription2)
                    .addComponent(txtTotalPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescription3)
                    .addComponent(txtFileString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUploadAssignment))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnSubmitAssignments))
                .addContainerGap(242, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    public void populateAssignmentFields()
    {
        txtDescription.setText(assignment.getDescription());
        txtDueDate.setText(assignment.getDueDate());
        txtTotalPoints.setText(String.valueOf(assignment.getTotalMarks()));
        
    }
    
    private void txtFileStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFileStringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFileStringActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AssignmentsListJPanel panel = new AssignmentsListJPanel(course);
        EachCourseJPanel.jSplitPane1.setRightComponent(panel);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnUploadAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadAssignmentActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File photo = chooser.getSelectedFile();
        filename = photo.getAbsolutePath();
        txtFileString.setText(filename);
    }//GEN-LAST:event_btnUploadAssignmentActionPerformed

    private void btnSubmitAssignmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitAssignmentsActionPerformed
        // TODO add your handling code here:
        StudentAssignment studentAssignment = new StudentAssignment();
        studentAssignment.setAssignmentId(assignment.getAssignmentId());
        studentAssignment.setStudentId(StudentDirectory.currentUser.getStudentId());
        studentAssignment.setFilePath(filename);
        studentAssignment.setCourseId(course.getCourseId());
        studentAssignment.setTotalMarks(Integer.parseInt(txtTotalPoints.getText()));
        studentAssignment.setStatus("Submitted");
        StudentAssignmentDirectory.assignmentSubmissionDirectory.put(assignment.getAssignmentId(), studentAssignment);
        
        
    }//GEN-LAST:event_btnSubmitAssignmentsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmitAssignments;
    private javax.swing.JButton btnUploadAssignment;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblDescription1;
    private javax.swing.JLabel lblDescription2;
    private javax.swing.JLabel lblDescription3;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtDueDate;
    private javax.swing.JTextField txtFileString;
    private javax.swing.JTextField txtTotalPoints;
    // End of variables declaration//GEN-END:variables
}
