/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.StudentWorkAreas;

import UserInterface.StudentWorkAreas.CourseDetailsJPanel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;
import model.courses.Assignment;
import model.courses.AssignmentDirectory;
import model.courses.Course;
import model.courses.CourseDirectory;
import model.courses.Schedule;
import model.courses.ScheduleDirectory;
import model.professors.ProfessorDirectory;
import model.student.StudentDirectory;

/**
 *
 * @author anirudh
 */
public class ListCourseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ListCourseJPanel
     */
    public ListCourseJPanel() {
        initComponents();
        populateCourseTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourseList = new javax.swing.JTable();
        btnViewCourse = new javax.swing.JButton();

        tblCourseList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course ID", "Course Name", "Credits", "Term"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCourseList);

        btnViewCourse.setText("View Course");
        btnViewCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(589, 589, 589)
                        .addComponent(btnViewCourse)))
                .addContainerGap(413, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnViewCourse)
                .addContainerGap(292, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void populateCourseTable()
    {
              ArrayList <Course> courseForProgram = CourseDirectory.getCoursesForPrograms(StudentDirectory.currentUser.getProgramId());
      
      DefaultTableModel model = (DefaultTableModel) tblCourseList.getModel();
        model.setRowCount(0);
        
        
        for(Course course : courseForProgram)
        {
            Object[] row = new Object[4];
            row[0] = course.getCourseId();
            row[1] = course.getTitle();
            row[2] = course.getCredits();
            row[3] = course.getAvailability();
            model.addRow(row);
        }
    }
    
    private void btnViewCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCourseActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCourseList.getSelectedRow();
        if(selectedRow >= 0)
        {

            {   
//                System.out.println(selectedRow);
                Course course = CourseDirectory.searchCourse((Integer)tblCourseList.getValueAt(selectedRow, 0));
                CourseDetailsJPanel panel = new CourseDetailsJPanel(course);
                StudentDashboardJPanel.jSplitPane1.setRightComponent(panel);
                
            }
            
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please select a course to view");
        }  

        
    }//GEN-LAST:event_btnViewCourseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewCourse;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCourseList;
    // End of variables declaration//GEN-END:variables
}
