/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.FacultyWorkAreas;

import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;
import UserInterface.AdminWorkAreas.AdminWorkArea;
import UserInterface.FacultyWorkAreas.FacultyDashboardJPanel;
import UserInterface.StudentWorkAreas.MainJFrame;
import UserInterface.StudentWorkAreas.StudentDashboardJPanel;
import javax.swing.JOptionPane;
import model.admin.Admin;
import model.admin.AdminDirectory;
import model.professors.Professor;
import model.professors.ProfessorDirectory;
import model.student.Student;
import model.student.StudentDirectory;

/**
 *
 * @author anirudh
 */
public class FacultyLoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FacultyLoginJPanel
     */
    public FacultyLoginJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogin = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        btnRegister1 = new javax.swing.JButton();
        lblDegreesOffered = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblUsername.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblUsername.setText("Username: ");

        lblPassword.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblPassword.setText("Password: ");

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblTitle.setText("Welcome to Coursera Faculty login");

        btnRegister1.setText("Contact us");
        btnRegister1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegister1ActionPerformed(evt);
            }
        });

        lblDegreesOffered.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblDegreesOffered.setText("Want to become a coursera teacher?");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(532, 532, 532)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnLogin)
                                .addGap(118, 118, 118))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblPassword)
                                                .addComponent(lblUsername))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtUsername)
                                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(lblTitle)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblDegreesOffered)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnRegister1)
                                    .addGap(29, 29, 29))))))
                .addContainerGap(592, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(btnBack)
                .addGap(43, 43, 43)
                .addComponent(lblTitle)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword))
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister1)
                    .addComponent(lblDegreesOffered))
                .addContainerGap(319, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnRegister1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegister1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegister1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        MainJFrame.changeScreen(MainJFrame.LandingPageJPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        
        Admin admin = AdminDirectory.getRequiredUser(txtUsername.getText());
        
        Student studentUser = StudentDirectory.getRequiredUser(txtUsername.getText());
        
        Professor loginUser = ProfessorDirectory.getRequiredUser(txtUsername.getText());
        
        int hashedInputPassword = Professor.hashPassword(String.valueOf(txtPassword.getText()));
        
        if(admin != null)
        {
                if (AdminDirectory.canLogin(txtUsername.getText(), hashedInputPassword)) {
                // Proceed with the login process, maybe open a new window or panel
                AdminDirectory.updateCurrentAdmin(admin);
                JOptionPane.showMessageDialog(this, "Login Successful");
                AdminWorkArea panel = new AdminWorkArea();
                MainJFrame.changeScreen(panel);
            }
            
        }
        
        else if( studentUser != null)
        {
                if (StudentDirectory.canLogin(txtUsername.getText(), hashedInputPassword)) {
                // Proceed with the login process, maybe open a new window or panel
                StudentDirectory.updateCurrentUser(studentUser);
                JOptionPane.showMessageDialog(this, "Login Successful");
                StudentDashboardJPanel panel = new StudentDashboardJPanel();
                MainJFrame.changeScreen(panel);
            
        }
        }
        
        else{
        
        
        //Validation for username and password credentials
        if (ProfessorDirectory.canLogin(txtUsername.getText(), hashedInputPassword)) {
                // Proceed with the login process, maybe open a new window or panel
                ProfessorDirectory.updateCurrentProfessor(loginUser);
                JOptionPane.showMessageDialog(this, "Login Successful");
                FacultyDashboardJPanel panel = new FacultyDashboardJPanel();
                MainJFrame.changeScreen(panel);
            }
        }
        
        
//        UserAccount currentUser = UserAccountDirectory.AuthenticateUser(txtUsername.getText(), txtPassword.getText());
//        if(currentUser.profile.getRole().equals("Faculty"))
//        {
////                ProfessorDirectory.updateCurrentProfessor(loginUser);
////                JOptionPane.showMessageDialog(this, "Login Successful");
//                FacultyDashboardJPanel panel = new FacultyDashboardJPanel();
//                MainJFrame.changeScreen(panel);
//        }
            
        
            
            //reset both fields
            txtUsername.setText("");
            txtPassword.setText("");
    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister1;
    private javax.swing.JLabel lblDegreesOffered;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
