/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.FacultyWorkAreas;

import UserInterface.FacultyWorkAreas.FacultyCourseDetailsJPanel;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.courses.Assignment;
import model.courses.AssignmentDirectory;
import model.courses.Course;
import model.courses.CourseDirectory;
import model.courses.Schedule;
import model.courses.ScheduleDirectory;
import model.professors.ProfessorDirectory;

/**
 *
 * @author anirudh
 */
public class FacultyCourseSpecificAssignmentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CourseSpecificAssignmentJPanel
     */
    Course course;
    Assignment selectedAssignment;
    public FacultyCourseSpecificAssignmentJPanel(Course course) {
        this.course = course;
        initComponents();
        populateCourseSpecificAssignmentsTable();
    }

    FacultyCourseSpecificAssignmentJPanel() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourseSpecificAssignments = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        tblCourseSpecificAssignments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Assignment ID", "Section", "Title", "Due By", "Total points", "No. of Submissions"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCourseSpecificAssignments);

        jButton1.setText("Create Assignment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update Assignment");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("View Assignment");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addGap(26, 26, 26)
                .addComponent(jButton2)
                .addGap(340, 340, 340))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(194, 194, 194))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void populateCourseSpecificAssignmentsTable()
    {
      ArrayList <Schedule> professorSchedule = ScheduleDirectory.findScheduleForProfessor((ProfessorDirectory.currentProfessor).getProfessorId());
      ArrayList <Assignment> assignmentListForprofessor = AssignmentDirectory.findAssignmentForProfessor(professorSchedule);
      ArrayList <Assignment> assignmentListForCourse = AssignmentDirectory.findAssignmentForCourse(course.getCourseId(), assignmentListForprofessor);
      DefaultTableModel model = (DefaultTableModel) tblCourseSpecificAssignments.getModel();
        model.setRowCount(0);
        
        
        for(Assignment assignment : assignmentListForCourse)
        {
            Object[] row = new Object[6];
            row[0] = assignment.getAssignmentId();
            String section="";
            for(Schedule schedule: professorSchedule)
            {
                if(assignment.getScheduleId() == schedule.getScheduleId())
                {
                    section = schedule.getSection();
                }
            }
            
            row[1] = section;
            row[2] = assignment.getTitle();
            row[3] = assignment.getDueDate();
            row[4] = assignment.getTotalMarks();
            row[5] = "";
            model.addRow(row);  
            
        }        
    }
        
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FacultyIndirectCreateAssignmentJPanel panel = new FacultyIndirectCreateAssignmentJPanel(course);
        FacultyCourseDetailsJPanel.jSplitPane1.setRightComponent(panel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCourseSpecificAssignments.getSelectedRow();
        selectedAssignment = AssignmentDirectory.findAssignment((Integer) tblCourseSpecificAssignments.getValueAt(selectedRow, 0));
        System.out.println(selectedAssignment.getTitle());
        FacultyIndirectUpdateAssignment panel = new FacultyIndirectUpdateAssignment(course, selectedAssignment);
        FacultyCourseDetailsJPanel.jSplitPane1.setRightComponent(panel);
                
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCourseSpecificAssignments.getSelectedRow();
        selectedAssignment = AssignmentDirectory.findAssignment((Integer) tblCourseSpecificAssignments.getValueAt(selectedRow, 0));
        FacultyIndirectViewAssignment panel = new FacultyIndirectViewAssignment(course, selectedAssignment);
        FacultyCourseDetailsJPanel.jSplitPane1.setRightComponent(panel);
                
        
        
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCourseSpecificAssignments;
    // End of variables declaration//GEN-END:variables
}
