/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.FacultyWorkAreas;

import UserInterface.FacultyWorkAreas.FacultyDashboardJPanel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.courses.Assignment;
import model.courses.AssignmentDirectory;
import model.courses.Schedule;
import model.courses.ScheduleDirectory;
import model.professors.ProfessorDirectory;
import model.student.Student;
import model.student.StudentAssignment;
import model.student.StudentAssignmentDirectory;

/**
 *
 * @author anirudh
 */
public class FacultyGradeDashboardJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FacultyGradeDashboardJPanel
     */
    public FacultyGradeDashboardJPanel() {
        initComponents();
        populateStudentAssignments();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAssignmentGrades = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Grade Assignments");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setText("Sort by course: ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblAssignmentGrades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Course Name", "Assignment ID", "Student ID", "Status", "Score"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAssignmentGrades);

        jButton1.setText("Grade Assignment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(581, 581, 581)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(545, 545, 545)
                        .addComponent(jLabel1)))
                .addContainerGap(380, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jButton1)
                .addContainerGap(296, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    public void populateStudentAssignments()
    {
        //        System.out.println("Current professor: "+ ProfessorDirectory.currentProfessor.getProfessorName() +" "+ ProfessorDirectory.currentProfessor.getProfessorId());
        ArrayList <Schedule> professorSchedule = ScheduleDirectory.findScheduleForProfessor(ProfessorDirectory.currentProfessor.getProfessorId());
        System.out.println(professorSchedule.size());
        ArrayList<Assignment> professorAssignments = AssignmentDirectory.findAssignmentForProfessor(ScheduleDirectory.scheduleForProfessor(ProfessorDirectory.currentProfessor.getProfessorId()));
        DefaultTableModel model = (DefaultTableModel) tblAssignmentGrades.getModel();
        model.setRowCount(0);
        
        
        for(Assignment assignment : professorAssignments)
        {
            ArrayList<Student> listStudents = StudentAssignmentDirectory.fetchStudentsForAssignment(assignment.getAssignmentId());
            for(Student student: listStudents)
            {
            Object[] row = new Object[5];
            
            row[0] = assignment.getCourseId();
            
            
            row[1] = assignment.getAssignmentId();
            row[2] = student.getStudentId();
            row[3] = StudentAssignmentDirectory.findSubmissionStatus(assignment.getAssignmentId(), student.getStudentId());
            row[4] = StudentAssignmentDirectory.findSubmissionScore(assignment.getAssignmentId(), student.getStudentId());
            model.addRow(row); 
            }
            
        }
    }
            
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                int selectedRow = tblAssignmentGrades.getSelectedRow();
        if(selectedRow >= 0)
        {

            {   
//                System.out.println(selectedRow);
                StudentAssignment chosenAssignment = StudentAssignmentDirectory.searchSubmission((Integer)tblAssignmentGrades.getValueAt(selectedRow, 1), (Integer)tblAssignmentGrades.getValueAt(selectedRow, 2));
                DirectGradeAssignmentJPanel panel = new DirectGradeAssignmentJPanel(chosenAssignment.getAssignmentId(), chosenAssignment);
                FacultyDashboardJPanel.jSplitPane1.setRightComponent(panel);
                
            }
            
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please select a assignment to grade");
        } 
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAssignmentGrades;
    // End of variables declaration//GEN-END:variables
}
